home:
  path: /
  defaults: { _controller: 'Front\Controllers\IndexController::index' }

activation:
  path: /activation
  defaults: { _controller: 'Front\Controllers\ActivationController::activation' }
  methods: [GET,POST]

recovery:
  path: /recovery
  defaults: { _controller: 'Front\Controllers\ActivationController::recovery' }
  methods: [GET,POST]