home:
  path: /
  defaults: { _controller: 'Front\Controllers\IndexController::index' }

faq:
  path: /faq
  defaults: { _controller: 'Front\Controllers\IndexController::faq' }

activation:
  path: /activation
  defaults: { _controller: 'Front\Controllers\ActivationController::activation' }
  methods: [GET,POST]

recovery:
  path: /recovery
  defaults: { _controller: 'Front\Controllers\ActivationController::recovery' }
  methods: [GET,POST]

audio_player:
  path: /audio/player/{trackId}
  defaults: { _controller: 'Front\Controllers\AudioController::index'}
  methods: [GET]

audio_list:
  path: /audio/list/{song}/{page}
  defaults: { _controller: 'Front\Controllers\AudioController::listAction', song: '', page: 1}
  methods: [GET]

user_upload_avatar:
  path: /user/upload-avatar
  defaults: { _controller: 'Front\Controllers\UserController::upload' }
  methods: [POST]

user_info:
  path: /user/info/{userId}
  defaults: { _controller: 'Front\Controllers\UserController::info' }
  methods: [GET, OPTIONS]

user_karma_details:
  path: /user/karma/{userId}
  defaults: { _controller: 'Front\Controllers\UserController::karmaDetails' }
  methods: [GET, OPTIONS]